application: pagepusher
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+ 
  script: in_mail.py
- url: /m.*
  script: messagehandler.py
  login: required
- url: /admin
  script: admin.py
  login: admin
- url: .*
  script: main.py
  login: required
